### ISSUE TITLE
Rotating card in Natours project 

### ISSUE THREAD

**Issue by Inzy-droid** [jonasschmedtmann/advanced-css-course#45]
only the back card side is rotating the front side card is fixed in place.

**Comment by jonasschmedtmann** [comment]
Hi Inzy,

Please post this question in the official course Q&A on Udemy, this is the central place for all questions, and makes this information available to all students of the course :)

--
Jonas Schmedtmann
jonas.io<http://jonas.io> / @jonasschmedtman<https://twitter.com/jonasschmedtman>

On June 23, 2020 at 10:53 PM, Inzy-droid (notifications@github.com<mailto:notifications@github.com>) wrote:
only the back card side is rotating the front side card is fixed in place.

**Comment by Inzy-droid** [comment]
Hi

Thanks for the reply but i managed to solve the issue. I needed to add
additional lines of code and create an extra div class and change the code
around a bit now its working perfectly fine

Thanks again
