### ISSUE TITLE
SASS Compile not working in NPM version 5.6.0

### ISSUE THREAD

**Issue by milonnj** [jonasschmedtmann/advanced-css-course#8]
SASS Compile not working. I have followed the tutorial but it's showing multiple errors. 
Here is the Command line
`npm run compile:sass`

It is coming up with these errors. 
`An output directory must be specified when compiling a directory
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ui@1.0.0 compile:sass: `node-sass sass/main.scss css/style.css`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ui@1.0.0 compile:sass script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Jahid\AppData\Roaming\npm-cache\_logs\2018-05-03T20_17_13_135Z-debug.log`

I am also attaching the scirpt package.json file. 
`{
  "name": "ui",
  "version": "1.0.0",
  "description": "Ui for QR Code generator",
  "main": "index.js",
  "scripts": {
    "compile:sass": "node-sass sass/main.scss css/style.css"
  },
  "author": "Jahid Anowar",
  "license": "ISC",
  "devDependencies": {
    "node-sass": "^4.9.0"
  }
}
`

**Comment by milonnj** [comment]
Problem Solved: There was a mistake in scss file name.

**Comment by mickeydp** [comment]
Here is the solution for everyone to this issues is not because of the version update.
It's because of the code you had written and pasted into the main.scss file or whatever yours scss file name be.
HERE GOES THE SOLUTION.
1:- ALWAYS USE THE LATEST THINGS WHEN IT COMES THE SOFTWARE.
  INSTALL THE LATEST NODE JS .https://nodejs.org/en/
 AND THE LASTEST SASS FOR THAT.  npm install node-sass -- save-dev.
2:-MOST IMPORTANT THING BECAUSE OF EVERYONE ARE GETTING THIS  ERROR  .
    YOURS CSS FILE CONTAINS COMMENTS WICH ARE DIFFERENT SAAS SO IT THROWS ERROR JUST DEL THE COMMENTS OR CHANGE IT TO SCSS TYPE . STILL CONFUSE ON THIS CHECK HOW T COMMENT IN SCSS. JUST GOOGLE IT.
IT WORKS 100% SURELY.
